import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { use } from "react"
import { TranslateContent } from "@/translateContent/translate";
import { En } from "@/messages/en";
import { Sv } from "@/messages/sv"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Params = {
  locale: string;
};

export default function RootLayout({children, params}: Readonly<{children: React.ReactNode; params: Promise<Params>}>) 
{
  console.log(params);
  
  const { locale } = use(params)
  console.log(locale)
  const messages = locale === "en" ? En : Sv
  return (
    <html
      lang={locale}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <TranslateContent value={messages}>
          {children}
        </TranslateContent>
      </body>
    </html>
  );
}
